/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examsystem;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author manas18
 */
public class Student extends javax.swing.JFrame {

    /**
     * Creates new form Student
     */
    public Student() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Slogin = new javax.swing.JButton();
        SNew = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        SLON = new javax.swing.JTabbedPane();
        sLogin = new javax.swing.JPanel();
        sLogin1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sLoginBtn = new javax.swing.JButton();
        sNew = new javax.swing.JPanel();
        sNew1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        sNumF = new javax.swing.JTextField();
        sEmailF = new javax.swing.JTextField();
        sIDF = new javax.swing.JTextField();
        sFNameF = new javax.swing.JTextField();
        sPassF = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        sCreateAF = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(930, 700));
        setMinimumSize(new java.awt.Dimension(930, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 204), 3));

        Slogin.setText("Login");
        Slogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SloginActionPerformed(evt);
            }
        });

        SNew.setText("New Account");
        SNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SNewActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examsystem/Image/Logo.png"))); // NOI18N

        jButton2.setBackground(new java.awt.Color(255, 0, 51));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SNew, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Slogin, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton2)
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(Slogin, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SNew, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(264, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 296, 700));

        SLON.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        sLogin1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Wide Latin", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 51));
        jLabel2.setText("Login");
        sLogin1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 114, 307, 73));
        sLogin1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 291, 338, 59));

        jPasswordField1.setText("jPasswordField1");
        sLogin1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 419, 338, 58));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Email Or Id");
        sLogin1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 243, -1, 47));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Password");
        sLogin1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 366, 152, 44));

        sLoginBtn.setBackground(new java.awt.Color(51, 153, 0));
        sLoginBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        sLoginBtn.setText("Login");
        sLoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sLoginBtnActionPerformed(evt);
            }
        });
        sLogin1.add(sLoginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 512, 146, 53));

        javax.swing.GroupLayout sLoginLayout = new javax.swing.GroupLayout(sLogin);
        sLogin.setLayout(sLoginLayout);
        sLoginLayout.setHorizontalGroup(
            sLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sLoginLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(sLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );
        sLoginLayout.setVerticalGroup(
            sLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sLoginLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(sLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        SLON.addTab("Login", sLogin);

        sNew.setMaximumSize(new java.awt.Dimension(623, 660));

        sNew1.setMaximumSize(new java.awt.Dimension(623, 660));
        sNew1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel3.setText("Create An Account");
        sNew1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 510, 70));
        sNew1.add(sNumF, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 270, 40));
        sNew1.add(sEmailF, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 270, 40));
        sNew1.add(sIDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 270, 40));
        sNew1.add(sFNameF, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 270, 40));

        sPassF.setText("jPasswordField2");
        sNew1.add(sPassF, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 500, 270, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("ID");
        sNew1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 100, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Full Name");
        sNew1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 130, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Number");
        sNew1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 100, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Password");
        sNew1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, 120, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("Email");
        sNew1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 100, 30));

        sCreateAF.setBackground(new java.awt.Color(51, 51, 255));
        sCreateAF.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        sCreateAF.setText("Create");
        sCreateAF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sCreateAFActionPerformed(evt);
            }
        });
        sNew1.add(sCreateAF, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 590, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examsystem/Image/pexels-pixabay-66869 (1).jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        sNew1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 20, 640, 710));

        javax.swing.GroupLayout sNewLayout = new javax.swing.GroupLayout(sNew);
        sNew.setLayout(sNewLayout);
        sNewLayout.setHorizontalGroup(
            sNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 684, Short.MAX_VALUE)
            .addGroup(sNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(sNewLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(sNew1, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        sNewLayout.setVerticalGroup(
            sNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(sNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(sNewLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(sNew1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        SLON.addTab("New Account", sNew);

        getContentPane().add(SLON, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, -60, -1, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SloginActionPerformed
        SLON.setSelectedIndex(0);
    }//GEN-LAST:event_SloginActionPerformed

    private void SNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SNewActionPerformed
        SLON.setSelectedIndex(1);
    }//GEN-LAST:event_SNewActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ExamSystem exS = new ExamSystem();
        exS.show();
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void sLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sLoginBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sLoginBtnActionPerformed

    private void sCreateAFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sCreateAFActionPerformed
       //Create Exam System File If it does not exist.
        File examSystem = new File("C:/ProgramData" + "//ExamSystem");
       File aLoginData = new File(examSystem.getAbsolutePath()+ "//Login.csv");
       if(!examSystem.exists()){
           examSystem.mkdir();
           
       }
       //Create All student Login Data file If it does not exist.
       if(!aLoginData.exists()){
               try {
                   aLoginData.createNewFile();
               } catch (IOException ex) {
                   Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
               }
           }
       //Add Create New Account data in CSV File..
       try{
           String sEmail = sEmailF.getText() + ",";
           String sId = sIDF.getText() + ",";
           String sFName = sFNameF.getText() + ",";
           String snum = sNumF.getText();
           String spass = sPassF.getText();
           
           FileWriter fw = new FileWriter(aLoginData.getAbsolutePath(), true);
           BufferedWriter br = new BufferedWriter(fw);
           br.write(sEmail  + sId  + sFName + snum  + "," +spass + "\n");
           br.close();
       
       }catch (IOException ex) {
                Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
            }
       
       
       
        
        JOptionPane.showMessageDialog(null, "Account Created!");
    }//GEN-LAST:event_sCreateAFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane SLON;
    private javax.swing.JButton SNew;
    private javax.swing.JButton Slogin;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton sCreateAF;
    private javax.swing.JTextField sEmailF;
    private javax.swing.JTextField sFNameF;
    private javax.swing.JTextField sIDF;
    private javax.swing.JPanel sLogin;
    private javax.swing.JPanel sLogin1;
    private javax.swing.JButton sLoginBtn;
    private javax.swing.JPanel sNew;
    private javax.swing.JPanel sNew1;
    private javax.swing.JTextField sNumF;
    private javax.swing.JPasswordField sPassF;
    // End of variables declaration//GEN-END:variables
}
