/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examsystem;

import static java.awt.PageAttributes.MediaType.C;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author manas18
 */
public class Teacher_Home extends javax.swing.JFrame {

    /**
     * Creates new form Teacher_Home
     */
    public Teacher_Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tCQMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tPanleHOme = new javax.swing.JButton();
        qCreate = new javax.swing.JButton();
        aQuestion = new javax.swing.JButton();
        aResult = new javax.swing.JButton();
        tLogout = new javax.swing.JButton();
        SNew2 = new javax.swing.JButton();
        tPanle = new javax.swing.JTabbedPane();
        tPanleWelcome = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        CNQWmessage = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cAQPanle = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        CNQHome = new javax.swing.JTabbedPane();
        cNQFirstPage = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        UnderLineCNQHome = new javax.swing.JLabel();
        tCName = new javax.swing.JTextField();
        tCBatch = new javax.swing.JTextField();
        tCCode = new javax.swing.JTextField();
        tCSection = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tCExamtype = new javax.swing.JTextField();
        tCExamCode = new javax.swing.JTextField();
        CNQHomeNext = new javax.swing.JButton();
        cNQSecPage = new javax.swing.JPanel();
        tCQQuestionLable = new javax.swing.JTextField();
        tCQOPtion4 = new javax.swing.JTextField();
        tCQOPtion3 = new javax.swing.JTextField();
        tCQOption2 = new javax.swing.JTextField();
        tCQOption1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tCQQnNumber = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        tCQQans = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        tCQFinishBTN = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        qPanle = new javax.swing.JPanel();
        tRSPanle1 = new javax.swing.JPanel();
        tQHeading = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tAQuestionsTable = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        tRSPanle = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tCQMenu.setBackground(new java.awt.Color(102, 102, 255));
        tCQMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 204), 3));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examsystem/Image/Logo.png"))); // NOI18N

        tPanleHOme.setText("Home");
        tPanleHOme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPanleHOmeActionPerformed(evt);
            }
        });

        qCreate.setText("Create Aquestion");
        qCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qCreateActionPerformed(evt);
            }
        });

        aQuestion.setText("Questions");
        aQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aQuestionActionPerformed(evt);
            }
        });

        aResult.setText("Results");
        aResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aResultActionPerformed(evt);
            }
        });

        tLogout.setText("LogOut");
        tLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tCQMenuLayout = new javax.swing.GroupLayout(tCQMenu);
        tCQMenu.setLayout(tCQMenuLayout);
        tCQMenuLayout.setHorizontalGroup(
            tCQMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tCQMenuLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(tCQMenuLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(tCQMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tPanleHOme, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aResult, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tCQMenuLayout.setVerticalGroup(
            tCQMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tCQMenuLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(tPanleHOme, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aResult, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        jPanel1.add(tCQMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 296, 700));

        SNew2.setText("Questions");
        SNew2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SNew2ActionPerformed(evt);
            }
        });
        jPanel1.add(SNew2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        tPanle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 153), 3));

        tPanleWelcome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 153), 2));
        tPanleWelcome.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 660, -1));

        CNQWmessage.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        CNQWmessage.setForeground(new java.awt.Color(0, 0, 153));
        CNQWmessage.setText("Welcome Back");
        tPanleWelcome.add(CNQWmessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 510, 140));

        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 204), 2));
        tPanleWelcome.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 460, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examsystem/Image/pexels-pixabay-459369.jpg"))); // NOI18N
        tPanleWelcome.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 660, 690));

        tPanle.addTab("tab4", tPanleWelcome);

        cAQPanle.setMaximumSize(new java.awt.Dimension(658, 720));
        cAQPanle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(255, 0, 102));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel5.setText("    Make A New Question");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 153), 3));
        cAQPanle.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 27, 658, 124));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Question Bio");

        UnderLineCNQHome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 153), 2));

        jLabel3.setText("Course Name");

        jLabel6.setText("Course Code");

        jLabel7.setText("Course Section");

        jLabel8.setText("Batch");

        jLabel9.setText("Exam code");

        jLabel10.setText("Exam Type");

        CNQHomeNext.setText("Next");
        CNQHomeNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CNQHomeNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cNQFirstPageLayout = new javax.swing.GroupLayout(cNQFirstPage);
        cNQFirstPage.setLayout(cNQFirstPageLayout);
        cNQFirstPageLayout.setHorizontalGroup(
            cNQFirstPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cNQFirstPageLayout.createSequentialGroup()
                .addGroup(cNQFirstPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cNQFirstPageLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(UnderLineCNQHome, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cNQFirstPageLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(cNQFirstPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cNQFirstPageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(cNQFirstPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cNQFirstPageLayout.createSequentialGroup()
                        .addGroup(cNQFirstPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CNQHomeNext, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(cNQFirstPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tCName, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                                .addComponent(tCCode)
                                .addComponent(tCSection)
                                .addComponent(tCBatch)
                                .addComponent(tCExamtype, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tCExamCode, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cNQFirstPageLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(169, 169, 169))))
        );
        cNQFirstPageLayout.setVerticalGroup(
            cNQFirstPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cNQFirstPageLayout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UnderLineCNQHome)
                .addGap(55, 55, 55)
                .addGroup(cNQFirstPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tCName, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(cNQFirstPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tCCode, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cNQFirstPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tCSection, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cNQFirstPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tCBatch, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(16, 16, 16)
                .addGroup(cNQFirstPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tCExamCode, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cNQFirstPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tCExamtype, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addComponent(CNQHomeNext, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CNQHome.addTab("Question", cNQFirstPage);

        cNQSecPage.setMaximumSize(new java.awt.Dimension(658, 600));

        tCQQuestionLable.setBorder(null);

        tCQOPtion4.setBorder(null);

        tCQOPtion3.setBorder(null);

        tCQOption2.setBorder(null);

        tCQOption1.setBorder(null);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("1");
        jLabel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setText("2");
        jLabel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setText("4");
        jLabel16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setText("3");
        jLabel17.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Enter Your Question: ");

        tCQQnNumber.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tCQQnNumber.setBorder(null);
        tCQQnNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCQQnNumberActionPerformed(evt);
            }
        });

        jButton1.setText("Show");
        jButton1.setBorder(new javax.swing.border.MatteBorder(null));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Question Number:");

        tCQQans.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel20.setText("Answer Index");

        jButton2.setText("Next");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tCQFinishBTN.setText("Finish");
        tCQFinishBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCQFinishBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cNQSecPageLayout = new javax.swing.GroupLayout(cNQSecPage);
        cNQSecPage.setLayout(cNQSecPageLayout);
        cNQSecPageLayout.setHorizontalGroup(
            cNQSecPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cNQSecPageLayout.createSequentialGroup()
                .addGap(0, 28, Short.MAX_VALUE)
                .addGroup(cNQSecPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(26, 26, 26)
                .addGroup(cNQSecPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(cNQSecPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tCQOPtion4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
                        .addComponent(tCQOption1, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(tCQOPtion3, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tCQOption2, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(cNQSecPageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cNQSecPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tCQQuestionLable)
                    .addGroup(cNQSecPageLayout.createSequentialGroup()
                        .addGroup(cNQSecPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(cNQSecPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cNQSecPageLayout.createSequentialGroup()
                                .addComponent(tCQQnNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58))))))
            .addGroup(cNQSecPageLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tCQQans, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(tCQFinishBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );
        cNQSecPageLayout.setVerticalGroup(
            cNQSecPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cNQSecPageLayout.createSequentialGroup()
                .addGroup(cNQSecPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cNQSecPageLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(cNQSecPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(jLabel18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cNQSecPageLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tCQQnNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addComponent(tCQQuestionLable, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(cNQSecPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(tCQOption1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cNQSecPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cNQSecPageLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18))
                    .addComponent(tCQOption2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(cNQSecPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cNQSecPageLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel17))
                    .addGroup(cNQSecPageLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tCQOPtion3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cNQSecPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tCQOPtion4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cNQSecPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tCQQans, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cNQSecPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tCQFinishBTN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        CNQHome.addTab("Question Bio", cNQSecPage);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        CNQHome.addTab("tab3", jPanel4);

        cAQPanle.add(CNQHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 650, 750));

        tPanle.addTab("tab2", cAQPanle);

        tQHeading.setBackground(new java.awt.Color(255, 0, 102));
        tQHeading.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        tQHeading.setText("            All Question");
        tQHeading.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 153), 3));

        tAQuestionsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Batch", "Course Code", "Section", "Exam Type", "Date", "Joining Code"
            }
        ));
        jScrollPane1.setViewportView(tAQuestionsTable);

        jTextField1.setText("Enter Your Question Code");

        jButton3.setText("View");

        javax.swing.GroupLayout tRSPanle1Layout = new javax.swing.GroupLayout(tRSPanle1);
        tRSPanle1.setLayout(tRSPanle1Layout);
        tRSPanle1Layout.setHorizontalGroup(
            tRSPanle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tRSPanle1Layout.createSequentialGroup()
                .addComponent(tQHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tRSPanle1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(tRSPanle1Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tRSPanle1Layout.setVerticalGroup(
            tRSPanle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tRSPanle1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(tQHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(tRSPanle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        javax.swing.GroupLayout qPanleLayout = new javax.swing.GroupLayout(qPanle);
        qPanle.setLayout(qPanleLayout);
        qPanleLayout.setHorizontalGroup(
            qPanleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 658, Short.MAX_VALUE)
            .addGroup(qPanleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(qPanleLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(tRSPanle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        qPanleLayout.setVerticalGroup(
            qPanleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
            .addGroup(qPanleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(qPanleLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(tRSPanle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        tPanle.addTab("tab3", qPanle);

        jLabel4.setBackground(new java.awt.Color(255, 0, 102));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel4.setText("    All Student's Results");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 153), 3));

        javax.swing.GroupLayout tRSPanleLayout = new javax.swing.GroupLayout(tRSPanle);
        tRSPanle.setLayout(tRSPanleLayout);
        tRSPanleLayout.setHorizontalGroup(
            tRSPanleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tRSPanleLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        tRSPanleLayout.setVerticalGroup(
            tRSPanleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tRSPanleLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(567, Short.MAX_VALUE))
        );

        tPanle.addTab("tab1", tRSPanle);

        jPanel1.add(tPanle, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, -60, 660, 760));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void qCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qCreateActionPerformed
        tPanle.setSelectedIndex(1);//Create A New Question
        CNQHome.setSelectedIndex(0);
    }//GEN-LAST:event_qCreateActionPerformed

    private void tLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tLogoutActionPerformed
        ExamSystem tLO = new ExamSystem();//Log Out
        tLO.show();
        dispose();
    }//GEN-LAST:event_tLogoutActionPerformed

    private void aQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aQuestionActionPerformed
        tPanle.setSelectedIndex(2);//All Question
    }//GEN-LAST:event_aQuestionActionPerformed

    private void SNew2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SNew2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SNew2ActionPerformed

    private void aResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aResultActionPerformed
        tPanle.setSelectedIndex(3);//Result
        
    }//GEN-LAST:event_aResultActionPerformed

    private void tPanleHOmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPanleHOmeActionPerformed
        tPanle.setSelectedIndex(0);//HOme
    }//GEN-LAST:event_tPanleHOmeActionPerformed
    String tCourseName, tCourseCode, tCourseSec, tBatch, tExamCode, tExamType, tQuestionPath;
     int tQCount = 1;   
        
/**************************************************************************************************************
 *                                          Question Information Receive
 **************************************************************************************************************/
  public File fileFHPathandCode = new File("C:/ProgramData/ExamSystem", "ExamCodePath.csv");
  
    //Create A New Question first Page Next Button..............
    private void CNQHomeNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CNQHomeNextActionPerformed
        
        //Create Newfile And catch value form textfield..........
        
        File file = new File("C:/ProgramData/ExamSystem" + "//Question");
        tBatch =tCBatch.getText(); 
        File fileBatchName = new File(file, tBatch);
        tCourseCode = tCCode.getText();
        File fileCourseCode = new File(fileBatchName,tCourseCode);
        tCourseSec = tCSection.getText();
        File fileCourseSection = new File(fileCourseCode, tCourseSec);
        tExamType = tCExamtype.getText();
        File fileExamType = new File(fileCourseSection, tExamType);
        tExamCode = tCExamCode.getText();
        tExamCode = tExamCode + ".csv";
        File fileExamcode = new File(fileExamType, tExamCode);
        tQuestionPath = fileExamcode.getAbsolutePath();
        
        tCourseName =tCName.getText();
        
        
        
        
        //Make Sure All There Are No Empty Field..................
        if(tCourseName.isEmpty() || tCourseCode.isEmpty() || tCourseSec.isEmpty() ||  tBatch.isEmpty() || tExamCode.isEmpty() || tExamType.isEmpty()){
            if(tCourseName.isEmpty()){
                JOptionPane.showMessageDialog(null, "Please Give A course Name!", "Fill All..", JOptionPane.ERROR_MESSAGE);
                
            }else if(tCourseCode.isEmpty()){
                JOptionPane.showMessageDialog(null, "Input A Course Code!!", "Fill All", JOptionPane.ERROR_MESSAGE);
            }else if(tCourseSec.isEmpty()){
                JOptionPane.showMessageDialog(null, "Input A Course Section.!", "Fill All", JOptionPane.ERROR_MESSAGE);
                
            }else if(tBatch.isEmpty()){
                JOptionPane.showMessageDialog(null, "Input A Batch Name.!", "Fill All", JOptionPane.ERROR_MESSAGE);
                
            }else if(tExamCode.isEmpty()){
                JOptionPane.showMessageDialog(null, "Please Give An Exam Code.!", "Fill All", JOptionPane.ERROR_MESSAGE);
                
            }else if(tExamType.isEmpty()){
                JOptionPane.showMessageDialog(null, "Please Give An Exam Name Of Type.!", "Fill All", JOptionPane.ERROR_MESSAGE);
                
            }
        }else{
          //File Create For Question Position....
        if(!file.exists()){
            file.mkdir();
        }
        
        if(!fileBatchName.exists()){
            fileBatchName.mkdir();
        }
        
        if(!fileCourseCode.exists()){
            fileCourseCode.mkdir();
        }
        if(!fileCourseSection.exists()){
            fileCourseSection.mkdir();
        }
        
        if(!fileExamType.exists()){
            fileExamType.mkdir();
        }
        
        if(!fileExamcode.exists()){
            try {
                fileExamcode.createNewFile();
                
            } catch (IOException ex) {
                Logger.getLogger(Teacher_Home.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        //Qourse Code And Path callect.......................
        if(!fileFHPathandCode.exists()){
            try {
                fileFHPathandCode.createNewFile();
                String temcodePath = tCExamCode.getText();
                
                FileWriter fw = new FileWriter(fileFHPathandCode,true);
                try (BufferedWriter bw = new BufferedWriter(fw)) { 
                    bw.write("Code" + "," + "Path" + "\n");
                    bw.write(temcodePath + "," + tQuestionPath + "\n");
                    bw.close();
                }
                
            } catch (IOException ex) {
                Logger.getLogger(Teacher_Home.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }else{
            String temcodePath = tCExamCode.getText();
            try {
                FileWriter fw = new FileWriter(fileFHPathandCode,true);
                BufferedWriter bw = new BufferedWriter(fw);
                bw.write(temcodePath + "," + tQuestionPath + "\n");
                
            } catch (IOException ex) {
                Logger.getLogger(Teacher_Home.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
        //Result Table expor..................
        String tresultexportLine = tBatch+ "," + tCourseSec + "," + tCourseSec + "," +tExamType + "," +java.time.LocalDate.now() +","+tCExamCode.getText() ;
        DefaultTableModel tAQtable = (DefaultTableModel)tAQuestionsTable.getModel();
        String[] row = tresultexportLine.toString().split(",");
        tAQtable.addRow(row);
        
            CNQHome.setSelectedIndex(1);
            tCQQnNumber.setText(String.valueOf(tQCount));//Display Question Count..........
        }
        
        
        
        
        
        
        
    }//GEN-LAST:event_CNQHomeNextActionPerformed
/********************************************************************************************************
                                            Question Receive
*********************************************************************************************************/
    
    

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
           tCQQnNumber.setText(String.valueOf(tQCount));//Display Question Count.........         
        //Receive Data from Textfield..............
        
        
        String tQQuestion, tQoption1, tQoption2, tQOption3, tQOption4, tQOptionAns;
        
        tQQuestion = tCQQuestionLable.getText();
        tQoption1 = tCQOption1.getText();
        tQoption2 = tCQOption2.getText();
        tQOption3 =tCQOPtion3.getText();
        tQOption4 = tCQOPtion4.getText();
        tQOptionAns = tCQQans.getText();
        
        //Make sure anti-epty file........................................
        
        if(tQQuestion.equals("") || tQoption1.equals("") || tQoption2.equals("") || tQOption3.equals("") ||tQOption4.equals("") || tQOptionAns.equals("")){
            if(tQQuestion.equals("")){
                JOptionPane.showMessageDialog(null, "Pleae Insert A Question!");
            } else if(tQoption1.equals("")){
                JOptionPane.showMessageDialog(null, "Pleae Set Option One!");
            }else if(tQoption2.equals("")){
                JOptionPane.showMessageDialog(null, "Pleae Set Option Two!");
            }else if(tQOption3.equals("")){
                JOptionPane.showMessageDialog(null, "Pleae Set Option Three!");
            }else if(tQOption4.equals("")){
                JOptionPane.showMessageDialog(null, "Pleae Set Option Four!");
            }else if(tQOptionAns.equals("")){
                JOptionPane.showMessageDialog(null, "Pleae A Question ans Without spase!");
            } 
        }else{
            //Write Data in cvs file...................
        
            try{
                
                FileWriter fw = new FileWriter(tQuestionPath,true);
                BufferedWriter bw = new BufferedWriter(fw);
                bw.write(tQQuestion + "," + tQoption1+ "," + tQoption2+ "," + tQOption3 + "," + tQOption4 + "," + tQOptionAns +"\n");
                bw.close();
            } catch (IOException ex) {
                Logger.getLogger(Teacher_Home.class.getName()).log(Level.SEVERE, null, ex);
            }
                
            tQCount++;
            tCQQnNumber.setText(String.valueOf(tQCount));//Display Question Count.........
        }
        //make sure empty file..............................
        tCQQuestionLable.setText("");
        tCQOption1.setText("");
        tCQOption2.setText("");
        tCQOPtion3.setText("");
        tCQOPtion4.setText("");
        tCQQans.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tCQQnNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCQQnNumberActionPerformed
       
    }//GEN-LAST:event_tCQQnNumberActionPerformed

    private void tCQFinishBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCQFinishBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tCQFinishBTNActionPerformed
   
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teacher_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teacher_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teacher_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teacher_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teacher_Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane CNQHome;
    private javax.swing.JButton CNQHomeNext;
    private javax.swing.JLabel CNQWmessage;
    private javax.swing.JButton SNew2;
    private javax.swing.JLabel UnderLineCNQHome;
    private javax.swing.JButton aQuestion;
    private javax.swing.JButton aResult;
    private javax.swing.JPanel cAQPanle;
    private javax.swing.JPanel cNQFirstPage;
    private javax.swing.JPanel cNQSecPage;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton qCreate;
    private javax.swing.JPanel qPanle;
    private javax.swing.JTable tAQuestionsTable;
    private javax.swing.JTextField tCBatch;
    private javax.swing.JTextField tCCode;
    private javax.swing.JTextField tCExamCode;
    private javax.swing.JTextField tCExamtype;
    private javax.swing.JTextField tCName;
    private javax.swing.JButton tCQFinishBTN;
    private javax.swing.JPanel tCQMenu;
    private javax.swing.JTextField tCQOPtion3;
    private javax.swing.JTextField tCQOPtion4;
    private javax.swing.JTextField tCQOption1;
    private javax.swing.JTextField tCQOption2;
    private javax.swing.JTextField tCQQans;
    private javax.swing.JTextField tCQQnNumber;
    private javax.swing.JTextField tCQQuestionLable;
    private javax.swing.JTextField tCSection;
    private javax.swing.JButton tLogout;
    private javax.swing.JTabbedPane tPanle;
    private javax.swing.JButton tPanleHOme;
    private javax.swing.JPanel tPanleWelcome;
    private javax.swing.JLabel tQHeading;
    private javax.swing.JPanel tRSPanle;
    private javax.swing.JPanel tRSPanle1;
    // End of variables declaration//GEN-END:variables
}
