/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examsystem;

/**
 *
 * @author manas18
 */
public class Teacher_Home extends javax.swing.JFrame {

    /**
     * Creates new form Teacher_Home
     */
    public Teacher_Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tHomeMenu = new javax.swing.JPanel();
        qCreate = new javax.swing.JButton();
        tLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        aQuestion = new javax.swing.JButton();
        aResult = new javax.swing.JButton();
        SNew2 = new javax.swing.JButton();
        tPanle = new javax.swing.JTabbedPane();
        cAQPanle = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        qPanle = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tRSPanle = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tHomeMenu.setBackground(new java.awt.Color(102, 102, 255));
        tHomeMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 204), 3));

        qCreate.setText("Create Aquestion");
        qCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qCreateActionPerformed(evt);
            }
        });

        tLogout.setText("LogOut");
        tLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tLogoutActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examsystem/Image/Logo.png"))); // NOI18N

        jButton2.setBackground(new java.awt.Color(255, 0, 51));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        aQuestion.setText("Questions");
        aQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aQuestionActionPerformed(evt);
            }
        });

        aResult.setText("Results");
        aResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aResultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tHomeMenuLayout = new javax.swing.GroupLayout(tHomeMenu);
        tHomeMenu.setLayout(tHomeMenuLayout);
        tHomeMenuLayout.setHorizontalGroup(
            tHomeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tHomeMenuLayout.createSequentialGroup()
                .addGroup(tHomeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(tHomeMenuLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(tHomeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aResult, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tHomeMenuLayout.setVerticalGroup(
            tHomeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tHomeMenuLayout.createSequentialGroup()
                .addComponent(jButton2)
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(qCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aResult, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        jPanel1.add(tHomeMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 296, 700));

        SNew2.setText("Questions");
        SNew2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SNew2ActionPerformed(evt);
            }
        });
        jPanel1.add(SNew2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        tPanle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 153), 3));

        jLabel2.setText("Create");

        javax.swing.GroupLayout cAQPanleLayout = new javax.swing.GroupLayout(cAQPanle);
        cAQPanle.setLayout(cAQPanleLayout);
        cAQPanleLayout.setHorizontalGroup(
            cAQPanleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cAQPanleLayout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(jLabel2)
                .addContainerGap(388, Short.MAX_VALUE))
        );
        cAQPanleLayout.setVerticalGroup(
            cAQPanleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cAQPanleLayout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(jLabel2)
                .addContainerGap(471, Short.MAX_VALUE))
        );

        tPanle.addTab("tab2", cAQPanle);

        jLabel3.setText("Question");

        javax.swing.GroupLayout qPanleLayout = new javax.swing.GroupLayout(qPanle);
        qPanle.setLayout(qPanleLayout);
        qPanleLayout.setHorizontalGroup(
            qPanleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qPanleLayout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jLabel3)
                .addContainerGap(434, Short.MAX_VALUE))
        );
        qPanleLayout.setVerticalGroup(
            qPanleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qPanleLayout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(jLabel3)
                .addContainerGap(447, Short.MAX_VALUE))
        );

        tPanle.addTab("tab3", qPanle);

        jLabel4.setText("Result");

        javax.swing.GroupLayout tRSPanleLayout = new javax.swing.GroupLayout(tRSPanle);
        tRSPanle.setLayout(tRSPanleLayout);
        tRSPanleLayout.setHorizontalGroup(
            tRSPanleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tRSPanleLayout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jLabel4)
                .addContainerGap(414, Short.MAX_VALUE))
        );
        tRSPanleLayout.setVerticalGroup(
            tRSPanleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tRSPanleLayout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(jLabel4)
                .addContainerGap(441, Short.MAX_VALUE))
        );

        tPanle.addTab("tab1", tRSPanle);

        jPanel1.add(tPanle, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, -60, 660, 760));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void qCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qCreateActionPerformed
        tPanle.setSelectedIndex(0);
    }//GEN-LAST:event_qCreateActionPerformed

    private void tLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tLogoutActionPerformed
        ExamSystem tLO = new ExamSystem();
        tLO.show();
        dispose();
    }//GEN-LAST:event_tLogoutActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ExamSystem exS = new ExamSystem();
        exS.show();
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void aQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aQuestionActionPerformed
        tPanle.setSelectedIndex(1);
    }//GEN-LAST:event_aQuestionActionPerformed

    private void SNew2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SNew2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SNew2ActionPerformed

    private void aResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aResultActionPerformed
        tPanle.setSelectedIndex(2);
    }//GEN-LAST:event_aResultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teacher_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teacher_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teacher_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teacher_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teacher_Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SNew2;
    private javax.swing.JButton aQuestion;
    private javax.swing.JButton aResult;
    private javax.swing.JPanel cAQPanle;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton qCreate;
    private javax.swing.JPanel qPanle;
    private javax.swing.JPanel tHomeMenu;
    private javax.swing.JButton tLogout;
    private javax.swing.JTabbedPane tPanle;
    private javax.swing.JPanel tRSPanle;
    // End of variables declaration//GEN-END:variables
}
